### ISSUE TITLE
autoload.php not found when running php download.php

### ISSUE THREAD

**Issue by marmata** [Sammaye/pokemon-tv-dl#1]
Hi! Just used this very useful docker and discovered an issue. The installation process doesn't include a "compose install" and so when you run "php download.php" the interpreter throws out errors about not finding autoload.php. I needed to login into the container and run "composer install" to fix it. Works flawlessy now, thanks for this!

**Comment by Sammaye** [comment]
Hmm it should actually run composer install, there must be something wrong with the start.sh file, it must not be detecting the compser.json right

**Comment by IcedTint** [comment]
> Hi! Just used this very useful docker and discovered an issue. The installation process doesn't include a "compose install" and so when you run "php download.php" the interpreter throws out errors about not finding autoload.php. I needed to login into the container and run "composer install" to fix it. Works flawlessy now, thanks for this!

Can you expand on this? I'm having the same issue and have no idea on how I could rectify it

**Comment by Sammaye** [comment]
You can just connec to the docker box by doing:

$ docker exec -it container_name (I forgot it) bash
$ composer install

**Comment by Sammaye** [comment]
Updated readme a little to give some tutorial on how to install composer stuff
